apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: kube-system
spec:
  backoffLimit: 0
  template:
    spec:
      hostPID: true
      restartPolicy: Never
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:v0.8.0
        command: ["kube-bench", "run"]
        args:
          - "--benchmark"
          - "cis-1.24"

          # Skip filesystem checks (Talos-safe)
          - "--skip"
          - "1.1.1,1.1.2,1.1.3,1.1.4,1.1.5"

        securityContext:
          privileged: true
